apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  name: taxi
  namespace: openshift-gitops
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: taxi
    weight: 100
  wildcardPolicy: None
